// Mocks generated by Mockito 5.4.4 from annotations
// in price_tracker/test/repository_test/repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i2;
import 'package:internet_connection_checker/internet_connection_checker.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:price_tracker/features/home/data/data_sources/remote/home_remote_data_source.dart'
    as _i4;
import 'package:price_tracker/features/home/data/models/symbol_model.dart'
    as _i7;
import 'package:price_tracker/features/home/data/models/symbol_price_model.dart'
    as _i8;
import 'package:price_tracker/features/home/domain/entity/error_entity.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_1 extends _i1.SmartFake implements Duration {
  _FakeDuration_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAddressCheckResult_2 extends _i1.SmartFake
    implements _i3.AddressCheckResult {
  _FakeAddressCheckResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HomeRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRemoteDataSource extends _i1.Mock
    implements _i4.HomeRemoteDataSource {
  MockHomeRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.ErrorEntity, List<_i7.SymbolModel>>> getSymbols() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSymbols,
          [],
        ),
        returnValue: _i5
            .Future<_i2.Either<_i6.ErrorEntity, List<_i7.SymbolModel>>>.value(
            _FakeEither_0<_i6.ErrorEntity, List<_i7.SymbolModel>>(
          this,
          Invocation.method(
            #getSymbols,
            [],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.ErrorEntity, List<_i7.SymbolModel>>>);

  @override
  _i5.Future<_i2.Either<_i6.ErrorEntity, String>> connectToWebSocket() =>
      (super.noSuchMethod(
        Invocation.method(
          #connectToWebSocket,
          [],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.ErrorEntity, String>>.value(
            _FakeEither_0<_i6.ErrorEntity, String>(
          this,
          Invocation.method(
            #connectToWebSocket,
            [],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.ErrorEntity, String>>);

  @override
  _i5.Future<_i2.Either<_i6.ErrorEntity, String>> subscribeToSymbol(
          String? symbol) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToSymbol,
          [symbol],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.ErrorEntity, String>>.value(
            _FakeEither_0<_i6.ErrorEntity, String>(
          this,
          Invocation.method(
            #subscribeToSymbol,
            [symbol],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.ErrorEntity, String>>);

  @override
  _i5.Future<_i2.Either<_i6.ErrorEntity, String>> unsubscribeFromSymbol(
          String? symbol) =>
      (super.noSuchMethod(
        Invocation.method(
          #unsubscribeFromSymbol,
          [symbol],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.ErrorEntity, String>>.value(
            _FakeEither_0<_i6.ErrorEntity, String>(
          this,
          Invocation.method(
            #unsubscribeFromSymbol,
            [symbol],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.ErrorEntity, String>>);

  @override
  _i5.Future<_i2.Either<_i6.ErrorEntity, String>> closeWebSocket() =>
      (super.noSuchMethod(
        Invocation.method(
          #closeWebSocket,
          [],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.ErrorEntity, String>>.value(
            _FakeEither_0<_i6.ErrorEntity, String>(
          this,
          Invocation.method(
            #closeWebSocket,
            [],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.ErrorEntity, String>>);

  @override
  _i5.Stream<_i2.Either<_i6.ErrorEntity, List<_i8.SymbolPriceUpdate>>>
      listenToPriceUpdates() => (super.noSuchMethod(
            Invocation.method(
              #listenToPriceUpdates,
              [],
            ),
            returnValue: _i5.Stream<
                _i2
                .Either<_i6.ErrorEntity, List<_i8.SymbolPriceUpdate>>>.empty(),
          ) as _i5.Stream<
              _i2.Either<_i6.ErrorEntity, List<_i8.SymbolPriceUpdate>>>);
}

/// A class which mocks [InternetConnectionChecker].
///
/// See the documentation for Mockito's code generation for more information.
class MockInternetConnectionChecker extends _i1.Mock
    implements _i3.InternetConnectionChecker {
  MockInternetConnectionChecker() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Duration get checkInterval => (super.noSuchMethod(
        Invocation.getter(#checkInterval),
        returnValue: _FakeDuration_1(
          this,
          Invocation.getter(#checkInterval),
        ),
      ) as Duration);

  @override
  Duration get checkTimeout => (super.noSuchMethod(
        Invocation.getter(#checkTimeout),
        returnValue: _FakeDuration_1(
          this,
          Invocation.getter(#checkTimeout),
        ),
      ) as Duration);

  @override
  List<_i3.AddressCheckOptions> get addresses => (super.noSuchMethod(
        Invocation.getter(#addresses),
        returnValue: <_i3.AddressCheckOptions>[],
      ) as List<_i3.AddressCheckOptions>);

  @override
  set addresses(List<_i3.AddressCheckOptions>? value) => super.noSuchMethod(
        Invocation.setter(
          #addresses,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<bool> get hasConnection => (super.noSuchMethod(
        Invocation.getter(#hasConnection),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i3.InternetConnectionStatus> get connectionStatus =>
      (super.noSuchMethod(
        Invocation.getter(#connectionStatus),
        returnValue: _i5.Future<_i3.InternetConnectionStatus>.value(
            _i3.InternetConnectionStatus.connected),
      ) as _i5.Future<_i3.InternetConnectionStatus>);

  @override
  _i5.Stream<_i3.InternetConnectionStatus> get onStatusChange =>
      (super.noSuchMethod(
        Invocation.getter(#onStatusChange),
        returnValue: _i5.Stream<_i3.InternetConnectionStatus>.empty(),
      ) as _i5.Stream<_i3.InternetConnectionStatus>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  bool get isActivelyChecking => (super.noSuchMethod(
        Invocation.getter(#isActivelyChecking),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<_i3.AddressCheckResult> isHostReachable(
          _i3.AddressCheckOptions? options) =>
      (super.noSuchMethod(
        Invocation.method(
          #isHostReachable,
          [options],
        ),
        returnValue:
            _i5.Future<_i3.AddressCheckResult>.value(_FakeAddressCheckResult_2(
          this,
          Invocation.method(
            #isHostReachable,
            [options],
          ),
        )),
      ) as _i5.Future<_i3.AddressCheckResult>);
}
